/**
 * International Country/Region Configuration & AVS (Address Verification System) Standards
 *
 * Provides complete ISO 3166-1 alpha-2 countries and territories,
 * country-specific subdivision models (states/provinces),
 * and rigorous AVS validation rules for international payment networks
 * (Visa, Mastercard, American Express, Discover, JCB).
 */

export interface StateSubdivision {
  code: string;
  name: string;
}

export interface CountryConfig {
  code: string;
  name: string;
  nativeName?: string;
  hasStates: boolean;
  stateLabel: string;
  states?: StateSubdivision[];
  postalLabel: string;
  postalPlaceholder: string;
  postalRequired: boolean;
  postalPattern?: RegExp;
  isAvsStrict: boolean; // US, GB, CA, AU, NZ have strict AVS requirements
}

// ── US States & Territories (USPS 2-Letter Standard) ──────────
export const US_STATES: StateSubdivision[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'DC', name: 'District of Columbia' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  // US Territories / Military
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'GU', name: 'Guam' },
  { code: 'VI', name: 'U.S. Virgin Islands' },
  { code: 'AA', name: 'Armed Forces Americas' },
  { code: 'AE', name: 'Armed Forces Europe / ME' },
  { code: 'AP', name: 'Armed Forces Pacific' },
];

// ── Canadian Provinces & Territories (Canada Post Standard) ──
export const CA_PROVINCES: StateSubdivision[] = [
  { code: 'AB', name: 'Alberta' },
  { code: 'BC', name: 'British Columbia' },
  { code: 'MB', name: 'Manitoba' },
  { code: 'NB', name: 'New Brunswick' },
  { code: 'NL', name: 'Newfoundland and Labrador' },
  { code: 'NS', name: 'Nova Scotia' },
  { code: 'NT', name: 'Northwest Territories' },
  { code: 'NU', name: 'Nunavut' },
  { code: 'ON', name: 'Ontario' },
  { code: 'PE', name: 'Prince Edward Island' },
  { code: 'QC', name: 'Quebec' },
  { code: 'SK', name: 'Saskatchewan' },
  { code: 'YT', name: 'Yukon' },
];

// ── Australian States & Territories (Australia Post Standard) ─
export const AU_STATES: StateSubdivision[] = [
  { code: 'ACT', name: 'Australian Capital Territory' },
  { code: 'NSW', name: 'New South Wales' },
  { code: 'NT', name: 'Northern Territory' },
  { code: 'QLD', name: 'Queensland' },
  { code: 'SA', name: 'South Australia' },
  { code: 'TAS', name: 'Tasmania' },
  { code: 'VIC', name: 'Victoria' },
  { code: 'WA', name: 'Western Australia' },
];

// ── Top / Popular Payment Countries for Quick Selection ─────
export const POPULAR_COUNTRY_CODES = [
  'SG', // Singapore (Omise SG base)
  'US', // United States (AVS strict)
  'GB', // United Kingdom (AVS strict)
  'CA', // Canada (AVS strict)
  'AU', // Australia (AVS strict)
  'NZ', // New Zealand (AVS strict)
  'JP', // Japan
  'CN', // China
  'HK', // Hong Kong
  'TW', // Taiwan
  'MY', // Malaysia
  'TH', // Thailand
  'ID', // Indonesia
  'PH', // Philippines
  'VN', // Vietnam
  'KR', // South Korea
  'DE', // Germany
  'FR', // France
  'NL', // Netherlands
  'CH', // Switzerland
  'AE', // United Arab Emirates
  'IN', // India
];

// ── Comprehensive ISO 3166-1 alpha-2 Country Dictionary ────────
export const ALL_COUNTRIES: CountryConfig[] = [
  // ── Core AVS-Enforced Markets ──
  {
    code: 'SG',
    name: 'Singapore',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 048581 (6 digits)',
    postalRequired: true,
    postalPattern: /^\d{6}$/,
    isAvsStrict: true,
  },
  {
    code: 'US',
    name: 'United States',
    hasStates: true,
    stateLabel: 'State',
    states: US_STATES,
    postalLabel: 'ZIP Code',
    postalPlaceholder: 'e.g. 90210 or 90210-1234',
    postalRequired: true,
    postalPattern: /^\d{5}(-\d{4})?$/,
    isAvsStrict: true,
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Postcode',
    postalPlaceholder: 'e.g. SW1A 1AA or EC1A 1BB',
    postalRequired: true,
    // Royal Mail PAF Standard BS 7666
    postalPattern: /^[A-Z]{1,2}[0-9][A-Z0-9]?\s?[0-9][A-Z]{2}$/i,
    isAvsStrict: true,
  },
  {
    code: 'CA',
    name: 'Canada',
    hasStates: true,
    stateLabel: 'Province / Territory',
    states: CA_PROVINCES,
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. M5V 2T6 or K1A 0B1',
    postalRequired: true,
    // Standard Canadian Postal Code (A1A 1A1)
    postalPattern: /^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z]\s?\d[ABCEGHJ-NPRSTV-Z]\d$/i,
    isAvsStrict: true,
  },
  {
    code: 'AU',
    name: 'Australia',
    hasStates: true,
    stateLabel: 'State / Territory',
    states: AU_STATES,
    postalLabel: 'Postcode',
    postalPlaceholder: 'e.g. 2000 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: true,
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postcode',
    postalPlaceholder: 'e.g. 1010 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: true,
  },

  // ── Asia Pacific ──
  {
    code: 'AF',
    name: 'Afghanistan',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Postal Code',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    hasStates: true,
    stateLabel: 'Division',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 1205 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'BT',
    name: 'Bhutan',
    hasStates: true,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Postal Code',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'BN',
    name: 'Brunei',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. BB3913',
    postalRequired: true,
    postalPattern: /^[A-Z]{2}\d{4}$/i,
    isAvsStrict: false,
  },
  {
    code: 'KH',
    name: 'Cambodia',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 12000 (5 digits)',
    postalRequired: false,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'CN',
    name: 'China',
    hasStates: true,
    stateLabel: 'Province / Municipality',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 100000 (6 digits)',
    postalRequired: true,
    postalPattern: /^\d{6}$/,
    isAvsStrict: false,
  },
  {
    code: 'HK',
    name: 'Hong Kong SAR',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Not applicable (leave empty or 999077)',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'IN',
    name: 'India',
    hasStates: true,
    stateLabel: 'State / UT',
    postalLabel: 'PIN Code',
    postalPlaceholder: 'e.g. 110001 (6 digits)',
    postalRequired: true,
    postalPattern: /^\d{6}$/,
    isAvsStrict: false,
  },
  {
    code: 'ID',
    name: 'Indonesia',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 10110 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'JP',
    name: 'Japan',
    hasStates: true,
    stateLabel: 'Prefecture',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 100-0001 or 1000001',
    postalRequired: true,
    postalPattern: /^\d{3}-?\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'KR',
    name: 'South Korea',
    hasStates: true,
    stateLabel: 'Province / City',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 03186 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'LA',
    name: 'Laos',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 01000',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'MO',
    name: 'Macau SAR',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Not applicable (optional)',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'MY',
    name: 'Malaysia',
    hasStates: true,
    stateLabel: 'State',
    postalLabel: 'Postcode',
    postalPlaceholder: 'e.g. 50450 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'MV',
    name: 'Maldives',
    hasStates: false,
    stateLabel: 'Atoll',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 20002',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'MN',
    name: 'Mongolia',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 14251 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'MM',
    name: 'Myanmar',
    hasStates: true,
    stateLabel: 'State / Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 11181 (5 digits)',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'NP',
    name: 'Nepal',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 44600 (5 digits)',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'PK',
    name: 'Pakistan',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 44000 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'PH',
    name: 'Philippines',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'ZIP Code',
    postalPlaceholder: 'e.g. 1000 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 00100 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'TW',
    name: 'Taiwan',
    hasStates: true,
    stateLabel: 'County / City',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 100 (3 or 5 digits)',
    postalRequired: true,
    postalPattern: /^\d{3,5}$/,
    isAvsStrict: false,
  },
  {
    code: 'TH',
    name: 'Thailand',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 10110 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'VN',
    name: 'Vietnam',
    hasStates: true,
    stateLabel: 'Province / City',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 700000 (5 or 6 digits)',
    postalRequired: false,
    postalPattern: /^\d{5,6}$/,
    isAvsStrict: false,
  },

  // ── Europe ──
  {
    code: 'AL',
    name: 'Albania',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 1001',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'AD',
    name: 'Andorra',
    hasStates: false,
    stateLabel: 'Parish',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. AD500',
    postalRequired: true,
    postalPattern: /^AD\d{3}$/i,
    isAvsStrict: false,
  },
  {
    code: 'AT',
    name: 'Austria',
    hasStates: true,
    stateLabel: 'State',
    postalLabel: 'PLZ (Postleitzahl)',
    postalPlaceholder: 'e.g. 1010 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'BE',
    name: 'Belgium',
    hasStates: false,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 1000 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 1000 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'HR',
    name: 'Croatia',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 10000 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'CY',
    name: 'Cyprus',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 1010 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 110 00',
    postalRequired: true,
    postalPattern: /^\d{3}\s?\d{2}$/,
    isAvsStrict: false,
  },
  {
    code: 'DK',
    name: 'Denmark',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postnummer',
    postalPlaceholder: 'e.g. 1050 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'EE',
    name: 'Estonia',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 10111 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'FI',
    name: 'Finland',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postinumero',
    postalPlaceholder: 'e.g. 00100 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'FR',
    name: 'France',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Code Postal',
    postalPlaceholder: 'e.g. 75001 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'DE',
    name: 'Germany',
    hasStates: true,
    stateLabel: 'Federal State',
    postalLabel: 'PLZ (Postleitzahl)',
    postalPlaceholder: 'e.g. 10115 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'GR',
    name: 'Greece',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 104 31',
    postalRequired: true,
    postalPattern: /^\d{3}\s?\d{2}$/,
    isAvsStrict: false,
  },
  {
    code: 'HU',
    name: 'Hungary',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 1011 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'IS',
    name: 'Iceland',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 101 (3 digits)',
    postalRequired: true,
    postalPattern: /^\d{3}$/,
    isAvsStrict: false,
  },
  {
    code: 'IE',
    name: 'Ireland',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Eircode',
    postalPlaceholder: 'e.g. D02 X285',
    postalRequired: true,
    postalPattern: /^[A-Z0-9]{3}\s?[A-Z0-9]{4}$/i,
    isAvsStrict: false,
  },
  {
    code: 'IT',
    name: 'Italy',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'CAP',
    postalPlaceholder: 'e.g. 00118 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'LV',
    name: 'Latvia',
    hasStates: false,
    stateLabel: 'Municipality',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. LV-1050',
    postalRequired: true,
    postalPattern: /^(LV-)?\d{4}$/i,
    isAvsStrict: false,
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
    hasStates: false,
    stateLabel: 'Municipality',
    postalLabel: 'PLZ',
    postalPlaceholder: 'e.g. 9490 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'LT',
    name: 'Lithuania',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. LT-01100',
    postalRequired: true,
    postalPattern: /^(LT-)?\d{5}$/i,
    isAvsStrict: false,
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    hasStates: false,
    stateLabel: 'Canton',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. L-1111 (4 digits)',
    postalRequired: true,
    postalPattern: /^(L-)?\d{4}$/i,
    isAvsStrict: false,
  },
  {
    code: 'MT',
    name: 'Malta',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. VLT 1115',
    postalRequired: true,
    postalPattern: /^[A-Z]{3}\s?\d{4}$/i,
    isAvsStrict: false,
  },
  {
    code: 'MC',
    name: 'Monaco',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Code Postal',
    postalPlaceholder: 'e.g. 98000',
    postalRequired: true,
    postalPattern: /^980\d{2}$/,
    isAvsStrict: false,
  },
  {
    code: 'NL',
    name: 'Netherlands',
    hasStates: false,
    stateLabel: 'Province',
    postalLabel: 'Postcode',
    postalPlaceholder: 'e.g. 1012 JS (4 digits + 2 letters)',
    postalRequired: true,
    postalPattern: /^\d{4}\s?[A-Z]{2}$/i,
    isAvsStrict: false,
  },
  {
    code: 'NO',
    name: 'Norway',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Postnummer',
    postalPlaceholder: 'e.g. 0010 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'PL',
    name: 'Poland',
    hasStates: true,
    stateLabel: 'Voivodeship',
    postalLabel: 'Kod pocztowy',
    postalPlaceholder: 'e.g. 00-001',
    postalRequired: true,
    postalPattern: /^\d{2}-\d{3}$/,
    isAvsStrict: false,
  },
  {
    code: 'PT',
    name: 'Portugal',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 1000-001',
    postalRequired: true,
    postalPattern: /^\d{4}-\d{3}$/,
    isAvsStrict: false,
  },
  {
    code: 'RO',
    name: 'Romania',
    hasStates: true,
    stateLabel: 'County',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 010011 (6 digits)',
    postalRequired: true,
    postalPattern: /^\d{6}$/,
    isAvsStrict: false,
  },
  {
    code: 'SM',
    name: 'San Marino',
    hasStates: false,
    stateLabel: 'Castello',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 47890 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'RS',
    name: 'Serbia',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 11000 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'SK',
    name: 'Slovakia',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'PSČ',
    postalPlaceholder: 'e.g. 811 01',
    postalRequired: true,
    postalPattern: /^\d{3}\s?\d{2}$/,
    isAvsStrict: false,
  },
  {
    code: 'SI',
    name: 'Slovenia',
    hasStates: false,
    stateLabel: 'Municipality',
    postalLabel: 'Poštna številka',
    postalPlaceholder: 'e.g. 1000 (4 digits)',
    postalRequired: true,
    postalPattern: /^(SI-)?\d{4}$/i,
    isAvsStrict: false,
  },
  {
    code: 'ES',
    name: 'Spain',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 28001 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'SE',
    name: 'Sweden',
    hasStates: false,
    stateLabel: 'County',
    postalLabel: 'Postnummer',
    postalPlaceholder: 'e.g. 111 22',
    postalRequired: true,
    postalPattern: /^\d{3}\s?\d{2}$/,
    isAvsStrict: false,
  },
  {
    code: 'CH',
    name: 'Switzerland',
    hasStates: true,
    stateLabel: 'Canton',
    postalLabel: 'PLZ / NPA',
    postalPlaceholder: 'e.g. 8001 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'TR',
    name: 'Turkey',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Posta Kodu',
    postalPlaceholder: 'e.g. 34000 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'UA',
    name: 'Ukraine',
    hasStates: true,
    stateLabel: 'Oblast',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 01001 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'VA',
    name: 'Vatican City',
    hasStates: false,
    stateLabel: 'Territory',
    postalLabel: 'Postal Code',
    postalPlaceholder: '00120',
    postalRequired: true,
    postalPattern: /^00120$/,
    isAvsStrict: false,
  },

  // ── Middle East & Central Asia ──
  {
    code: 'AM',
    name: 'Armenia',
    hasStates: false,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 0010 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. AZ1000',
    postalRequired: true,
    postalPattern: /^(AZ)?\d{4}$/i,
    isAvsStrict: false,
  },
  {
    code: 'BH',
    name: 'Bahrain',
    hasStates: false,
    stateLabel: 'Governorate',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 317 (3 or 4 digits, optional)',
    postalRequired: false,
    postalPattern: /^\d{3,4}$/,
    isAvsStrict: false,
  },
  {
    code: 'GE',
    name: 'Georgia',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 0100 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'IL',
    name: 'Israel',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 6100000 (7 digits)',
    postalRequired: true,
    postalPattern: /^\d{7}$/,
    isAvsStrict: false,
  },
  {
    code: 'JO',
    name: 'Jordan',
    hasStates: true,
    stateLabel: 'Governorate',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 11118 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
    hasStates: true,
    stateLabel: 'Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 010000 (6 digits)',
    postalRequired: true,
    postalPattern: /^\d{6}$/,
    isAvsStrict: false,
  },
  {
    code: 'KW',
    name: 'Kuwait',
    hasStates: false,
    stateLabel: 'Governorate',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 13001 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'LB',
    name: 'Lebanon',
    hasStates: false,
    stateLabel: 'Governorate',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 1107 2020',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'OM',
    name: 'Oman',
    hasStates: true,
    stateLabel: 'Governorate',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 100 (3 digits)',
    postalRequired: true,
    postalPattern: /^\d{3}$/,
    isAvsStrict: false,
  },
  {
    code: 'QA',
    name: 'Qatar',
    hasStates: false,
    stateLabel: 'Municipality',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Not applicable (optional)',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 12211 or 12211-1234',
    postalRequired: true,
    postalPattern: /^\d{5}(-\d{4})?$/,
    isAvsStrict: false,
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    hasStates: true,
    stateLabel: 'Emirate (e.g. Dubai, Abu Dhabi)',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Not applicable / 00000 (optional)',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
    hasStates: true,
    stateLabel: 'Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 100000 (6 digits)',
    postalRequired: true,
    postalPattern: /^\d{6}$/,
    isAvsStrict: false,
  },

  // ── Americas (Latin & South America) ──
  {
    code: 'AR',
    name: 'Argentina',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. C1002AA or 1002',
    postalRequired: true,
    postalPattern: /^([A-Z]\d{4}[A-Z]{3}|\d{4})$/i,
    isAvsStrict: false,
  },
  {
    code: 'BS',
    name: 'Bahamas',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Postal Code',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'BB',
    name: 'Barbados',
    hasStates: false,
    stateLabel: 'Parish',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. BB11000',
    postalRequired: true,
    postalPattern: /^BB\d{5}$/i,
    isAvsStrict: false,
  },
  {
    code: 'BM',
    name: 'Bermuda',
    hasStates: false,
    stateLabel: 'Parish',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. HM 11',
    postalRequired: true,
    postalPattern: /^[A-Z]{2}\s?[A-Z0-9]{2}$/i,
    isAvsStrict: false,
  },
  {
    code: 'BR',
    name: 'Brazil',
    hasStates: true,
    stateLabel: 'State',
    postalLabel: 'CEP',
    postalPlaceholder: 'e.g. 01001-000 or 01001000',
    postalRequired: true,
    postalPattern: /^\d{5}-?\d{3}$/,
    isAvsStrict: false,
  },
  {
    code: 'CL',
    name: 'Chile',
    hasStates: true,
    stateLabel: 'Region',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 8320000 (7 digits)',
    postalRequired: true,
    postalPattern: /^\d{7}$/,
    isAvsStrict: false,
  },
  {
    code: 'CO',
    name: 'Colombia',
    hasStates: true,
    stateLabel: 'Department',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 110111 (6 digits)',
    postalRequired: true,
    postalPattern: /^\d{6}$/,
    isAvsStrict: false,
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 10101 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 10101 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'EC',
    name: 'Ecuador',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 170150 (6 digits)',
    postalRequired: true,
    postalPattern: /^\d{6}$/,
    isAvsStrict: false,
  },
  {
    code: 'GT',
    name: 'Guatemala',
    hasStates: true,
    stateLabel: 'Department',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 01001 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'JM',
    name: 'Jamaica',
    hasStates: false,
    stateLabel: 'Parish',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 00000',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'MX',
    name: 'Mexico',
    hasStates: true,
    stateLabel: 'State',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 01000 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'PA',
    name: 'Panama',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Postal Code (optional)',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'PE',
    name: 'Peru',
    hasStates: true,
    stateLabel: 'Region',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 15001 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
    hasStates: false,
    stateLabel: 'Region',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Postal Code',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'UY',
    name: 'Uruguay',
    hasStates: true,
    stateLabel: 'Department',
    postalLabel: 'Código Postal',
    postalPlaceholder: 'e.g. 11000 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },

  // ── Africa & Other Territories ──
  {
    code: 'DZ',
    name: 'Algeria',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 16000 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'EG',
    name: 'Egypt',
    hasStates: true,
    stateLabel: 'Governorate',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 11511 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'GH',
    name: 'Ghana',
    hasStates: true,
    stateLabel: 'Region',
    postalLabel: 'Postal Code / Digital Address',
    postalPlaceholder: 'e.g. GA-183-9322',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'KE',
    name: 'Kenya',
    hasStates: true,
    stateLabel: 'County',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 00100 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'MA',
    name: 'Morocco',
    hasStates: true,
    stateLabel: 'Region',
    postalLabel: 'Code Postal',
    postalPlaceholder: 'e.g. 10000 (5 digits)',
    postalRequired: true,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'MU',
    name: 'Mauritius',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 11302 (5 digits)',
    postalRequired: false,
    postalPattern: /^\d{5}$/,
    isAvsStrict: false,
  },
  {
    code: 'NG',
    name: 'Nigeria',
    hasStates: true,
    stateLabel: 'State',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 100001 (6 digits, optional)',
    postalRequired: false,
    postalPattern: /^\d{6}$/,
    isAvsStrict: false,
  },
  {
    code: 'RW',
    name: 'Rwanda',
    hasStates: false,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Postal Code',
    postalRequired: false,
    isAvsStrict: false,
  },
  {
    code: 'ZA',
    name: 'South Africa',
    hasStates: true,
    stateLabel: 'Province',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'e.g. 8001 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'TN',
    name: 'Tunisia',
    hasStates: false,
    stateLabel: 'Governorate',
    postalLabel: 'Code Postal',
    postalPlaceholder: 'e.g. 1000 (4 digits)',
    postalRequired: true,
    postalPattern: /^\d{4}$/,
    isAvsStrict: false,
  },
  {
    code: 'UG',
    name: 'Uganda',
    hasStates: false,
    stateLabel: 'District',
    postalLabel: 'Postal Code',
    postalPlaceholder: 'Postal Code',
    postalRequired: false,
    isAvsStrict: false,
  },

  // ── Extended Global Alpha-2 Countries & Territories ──
  { code: 'AX', name: 'Åland Islands', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '22100', postalRequired: true, postalPattern: /^\d{5}$/, isAvsStrict: false },
  { code: 'AO', name: 'Angola', hasStates: true, stateLabel: 'Province', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'AI', name: 'Anguilla', hasStates: false, stateLabel: 'District', postalLabel: 'Postal Code', postalPlaceholder: 'AI-2640', postalRequired: false, isAvsStrict: false },
  { code: 'AG', name: 'Antigua and Barbuda', hasStates: false, stateLabel: 'Parish', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'AW', name: 'Aruba', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'BA', name: 'Bosnia and Herzegovina', hasStates: false, stateLabel: 'Canton', postalLabel: 'Postal Code', postalPlaceholder: '71000', postalRequired: true, postalPattern: /^\d{5}$/, isAvsStrict: false },
  { code: 'BW', name: 'Botswana', hasStates: false, stateLabel: 'District', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'BZ', name: 'Belize', hasStates: true, stateLabel: 'District', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'BO', name: 'Bolivia', hasStates: true, stateLabel: 'Department', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'CM', name: 'Cameroon', hasStates: true, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'CV', name: 'Cape Verde', hasStates: false, stateLabel: 'Municipality', postalLabel: 'Postal Code', postalPlaceholder: '7600', postalRequired: false, isAvsStrict: false },
  { code: 'KY', name: 'Cayman Islands', hasStates: false, stateLabel: 'District', postalLabel: 'Postal Code', postalPlaceholder: 'KY1-1100', postalRequired: false, isAvsStrict: false },
  { code: 'CI', name: "Côte d'Ivoire", hasStates: true, stateLabel: 'District', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'CW', name: 'Curaçao', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'ET', name: 'Ethiopia', hasStates: true, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '1000', postalRequired: false, isAvsStrict: false },
  { code: 'FO', name: 'Faroe Islands', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '100', postalRequired: true, postalPattern: /^\d{3}$/, isAvsStrict: false },
  { code: 'FJ', name: 'Fiji', hasStates: false, stateLabel: 'Division', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'PF', name: 'French Polynesia', hasStates: false, stateLabel: 'Archipelago', postalLabel: 'Postal Code', postalPlaceholder: '98714', postalRequired: true, postalPattern: /^\d{5}$/, isAvsStrict: false },
  { code: 'GI', name: 'Gibraltar', hasStates: false, stateLabel: 'Territory', postalLabel: 'Postal Code', postalPlaceholder: 'GX11 1AA', postalRequired: true, postalPattern: /^GX11\s?1AA$/i, isAvsStrict: true },
  { code: 'GL', name: 'Greenland', hasStates: false, stateLabel: 'Municipality', postalLabel: 'Postal Code', postalPlaceholder: '3900', postalRequired: true, postalPattern: /^\d{4}$/, isAvsStrict: false },
  { code: 'GP', name: 'Guadeloupe', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '97100', postalRequired: true, postalPattern: /^\d{5}$/, isAvsStrict: false },
  { code: 'GG', name: 'Guernsey', hasStates: false, stateLabel: 'Parish', postalLabel: 'Postal Code', postalPlaceholder: 'GY1 1AA', postalRequired: true, postalPattern: /^GY\d\s?\d[A-Z]{2}$/i, isAvsStrict: true },
  { code: 'GY', name: 'Guyana', hasStates: true, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'IM', name: 'Isle of Man', hasStates: false, stateLabel: 'Town', postalLabel: 'Postal Code', postalPlaceholder: 'IM1 1AA', postalRequired: true, postalPattern: /^IM\d\s?\d[A-Z]{2}$/i, isAvsStrict: true },
  { code: 'JE', name: 'Jersey', hasStates: false, stateLabel: 'Parish', postalLabel: 'Postal Code', postalPlaceholder: 'JE1 1AA', postalRequired: true, postalPattern: /^JE\d\s?\d[A-Z]{2}$/i, isAvsStrict: true },
  { code: 'LI', name: 'Liechtenstein', hasStates: false, stateLabel: 'Municipality', postalLabel: 'Postal Code', postalPlaceholder: '9490', postalRequired: true, postalPattern: /^\d{4}$/, isAvsStrict: false },
  { code: 'MK', name: 'North Macedonia', hasStates: false, stateLabel: 'Municipality', postalLabel: 'Postal Code', postalPlaceholder: '1000', postalRequired: true, postalPattern: /^\d{4}$/, isAvsStrict: false },
  { code: 'MG', name: 'Madagascar', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '101', postalRequired: false, isAvsStrict: false },
  { code: 'MT', name: 'Malta', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: 'VLT 1115', postalRequired: true, postalPattern: /^[A-Z]{3}\s?\d{4}$/i, isAvsStrict: false },
  { code: 'MQ', name: 'Martinique', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '97200', postalRequired: true, postalPattern: /^\d{5}$/, isAvsStrict: false },
  { code: 'MD', name: 'Moldova', hasStates: false, stateLabel: 'District', postalLabel: 'Postal Code', postalPlaceholder: 'MD-2000', postalRequired: true, postalPattern: /^(MD-)?\d{4}$/i, isAvsStrict: false },
  { code: 'ME', name: 'Montenegro', hasStates: false, stateLabel: 'Municipality', postalLabel: 'Postal Code', postalPlaceholder: '81000', postalRequired: true, postalPattern: /^\d{5}$/, isAvsStrict: false },
  { code: 'MZ', name: 'Mozambique', hasStates: true, stateLabel: 'Province', postalLabel: 'Postal Code', postalPlaceholder: '1100', postalRequired: false, isAvsStrict: false },
  { code: 'NA', name: 'Namibia', hasStates: true, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '9000', postalRequired: false, isAvsStrict: false },
  { code: 'NC', name: 'New Caledonia', hasStates: false, stateLabel: 'Province', postalLabel: 'Postal Code', postalPlaceholder: '98800', postalRequired: true, postalPattern: /^\d{5}$/, isAvsStrict: false },
  { code: 'PG', name: 'Papua New Guinea', hasStates: true, stateLabel: 'Province', postalLabel: 'Postal Code', postalPlaceholder: '111', postalRequired: false, isAvsStrict: false },
  { code: 'PY', name: 'Paraguay', hasStates: true, stateLabel: 'Department', postalLabel: 'Postal Code', postalPlaceholder: '1001', postalRequired: true, postalPattern: /^\d{4}$/, isAvsStrict: false },
  { code: 'RE', name: 'Réunion', hasStates: false, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '97400', postalRequired: true, postalPattern: /^\d{5}$/, isAvsStrict: false },
  { code: 'SN', name: 'Senegal', hasStates: true, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '10000', postalRequired: false, isAvsStrict: false },
  { code: 'SC', name: 'Seychelles', hasStates: false, stateLabel: 'District', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'SR', name: 'Suriname', hasStates: false, stateLabel: 'District', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
  { code: 'TZ', name: 'Tanzania', hasStates: true, stateLabel: 'Region', postalLabel: 'Postal Code', postalPlaceholder: '11101', postalRequired: false, isAvsStrict: false },
  { code: 'ZW', name: 'Zimbabwe', hasStates: true, stateLabel: 'Province', postalLabel: 'Postal Code', postalPlaceholder: 'Postal Code', postalRequired: false, isAvsStrict: false },
];

// Deduplicate and sort all countries alphabetically by English name
const countryMap = new Map<string, CountryConfig>();
for (const c of ALL_COUNTRIES) {
  if (!countryMap.has(c.code)) {
    countryMap.set(c.code, c);
  }
}

export const SORTED_ALL_COUNTRIES: CountryConfig[] = Array.from(countryMap.values()).sort(
  (a, b) => a.name.localeCompare(b.name),
);

export const POPULAR_COUNTRIES: CountryConfig[] = POPULAR_COUNTRY_CODES.map(
  (code) => countryMap.get(code)!,
).filter(Boolean);

/**
 * Retrieve country config by ISO 3166-1 alpha-2 code
 */
export function getCountryByCode(code: string): CountryConfig {
  const upper = code ? code.toUpperCase() : 'SG';
  return (
    countryMap.get(upper) || {
      code: upper,
      name: upper,
      hasStates: false,
      stateLabel: 'State / Region',
      postalLabel: 'Postal Code',
      postalPlaceholder: 'Postal / ZIP Code',
      postalRequired: true,
      isAvsStrict: false,
    }
  );
}

/**
 * Auto-format postal/ZIP code according to country specifications
 */
export function formatPostalCode(countryCode: string, raw: string): string {
  const c = countryCode.toUpperCase();
  const trimmed = raw.trim();

  // US: 5 digits or ZIP+4 (12345-6789)
  if (c === 'US') {
    const digits = trimmed.replace(/\D/g, '').slice(0, 9);
    if (digits.length > 5) {
      return `${digits.slice(0, 5)}-${digits.slice(5)}`;
    }
    return digits;
  }

  // Canada: A1A 1A1
  if (c === 'CA') {
    const cleaned = trimmed.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6);
    if (cleaned.length > 3) {
      return `${cleaned.slice(0, 3)} ${cleaned.slice(3)}`;
    }
    return cleaned;
  }

  // United Kingdom: SW1A 1AA (Standard Royal Mail space format)
  if (c === 'GB') {
    const cleaned = trimmed.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 7);
    if (cleaned.length > 3) {
      // Inward code is always the last 3 characters
      const outward = cleaned.slice(0, cleaned.length - 3);
      const inward = cleaned.slice(cleaned.length - 3);
      return `${outward} ${inward}`;
    }
    return cleaned;
  }

  // Netherlands: 1234 AB
  if (c === 'NL') {
    const cleaned = trimmed.toUpperCase().replace(/\s+/g, '').slice(0, 6);
    if (cleaned.length > 4) {
      return `${cleaned.slice(0, 4)} ${cleaned.slice(4)}`;
    }
    return cleaned;
  }

  // Japan: 123-4567
  if (c === 'JP') {
    const digits = trimmed.replace(/\D/g, '').slice(0, 7);
    if (digits.length > 3) {
      return `${digits.slice(0, 3)}-${digits.slice(3)}`;
    }
    return digits;
  }

  // Poland: 00-001
  if (c === 'PL') {
    const digits = trimmed.replace(/\D/g, '').slice(0, 5);
    if (digits.length > 2) {
      return `${digits.slice(0, 2)}-${digits.slice(2)}`;
    }
    return digits;
  }

  // Portugal: 1000-001
  if (c === 'PT') {
    const digits = trimmed.replace(/\D/g, '').slice(0, 7);
    if (digits.length > 4) {
      return `${digits.slice(0, 4)}-${digits.slice(4)}`;
    }
    return digits;
  }

  // Brazil: 01001-000
  if (c === 'BR') {
    const digits = trimmed.replace(/\D/g, '').slice(0, 8);
    if (digits.length > 5) {
      return `${digits.slice(0, 5)}-${digits.slice(5)}`;
    }
    return digits;
  }

  return raw;
}
